import type { Examination, Lesion, Profile, Reminder } from '@/lib/db/types';

export const VALIDATION_UI_PROFILE: Profile = {
  id: 'validation-ui-profile-self',
  nickname: '验证档案',
  gender: 'female',
  birth_year: 1988,
  avatar_uri: null,
  sort_order: 0,
  created_at: '2026-01-10T00:00:00.000Z',
  updated_at: '2026-04-20T00:00:00.000Z',
};

export const VALIDATION_UI_LESIONS: Lesion[] = [
  {
    id: 'validation-ui-lesion-thyroid',
    profile_id: VALIDATION_UI_PROFILE.id,
    disease_type: 'thyroid',
    label: '验证甲状腺右叶结节',
    location: '右叶上极',
    is_archived: 0,
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-lesion-breast',
    profile_id: VALIDATION_UI_PROFILE.id,
    disease_type: 'breast',
    label: '验证乳腺外上象限结节',
    location: '左乳外上象限',
    is_archived: 0,
    created_at: '2026-02-11T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-lesion-lung',
    profile_id: VALIDATION_UI_PROFILE.id,
    disease_type: 'lung',
    label: '验证肺右上叶结节',
    location: '右肺上叶尖段',
    is_archived: 0,
    created_at: '2026-03-02T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
  },
];

export const VALIDATION_UI_EXAMINATIONS: Examination[] = [
  {
    id: 'validation-ui-exam-thyroid-latest',
    lesion_id: 'validation-ui-lesion-thyroid',
    exam_date: '2026-04-20',
    hospital: '验证接口医院A',
    size_x: 9.1,
    size_y: 5.6,
    size_z: 4.8,
    tirads: '4a',
    echo_type: '低回声',
    border: '欠清',
    calcification: '点状强回声',
    blood_flow: '少量血流',
    birads: null,
    shape: null,
    orientation: null,
    lung_rads: null,
    density: null,
    morphology: null,
    pleural_pull: null,
    ai_raw_json: null,
    notes: null,
    created_at: '2026-04-20T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-exam-thyroid-middle',
    lesion_id: 'validation-ui-lesion-thyroid',
    exam_date: '2026-01-20',
    hospital: '验证接口医院A',
    size_x: 8.4,
    size_y: 5.1,
    size_z: 4.6,
    tirads: '3',
    echo_type: '低回声',
    border: '尚清',
    calcification: '无明显钙化',
    blood_flow: '少量血流',
    birads: null,
    shape: null,
    orientation: null,
    lung_rads: null,
    density: null,
    morphology: null,
    pleural_pull: null,
    ai_raw_json: null,
    notes: null,
    created_at: '2026-01-20T00:00:00.000Z',
    updated_at: '2026-01-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-exam-thyroid-baseline',
    lesion_id: 'validation-ui-lesion-thyroid',
    exam_date: '2025-10-20',
    hospital: '验证接口医院A',
    size_x: 7.7,
    size_y: 4.9,
    size_z: 4.1,
    tirads: '3',
    echo_type: '等回声',
    border: '清晰',
    calcification: '无明显钙化',
    blood_flow: '未见明显血流',
    birads: null,
    shape: null,
    orientation: null,
    lung_rads: null,
    density: null,
    morphology: null,
    pleural_pull: null,
    ai_raw_json: null,
    notes: null,
    created_at: '2025-10-20T00:00:00.000Z',
    updated_at: '2025-10-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-exam-breast-latest',
    lesion_id: 'validation-ui-lesion-breast',
    exam_date: '2026-04-18',
    hospital: '验证接口医院B',
    size_x: 13.2,
    size_y: 7.1,
    size_z: null,
    tirads: null,
    echo_type: null,
    border: null,
    calcification: null,
    blood_flow: null,
    birads: '3',
    shape: '椭圆形',
    orientation: '平行',
    lung_rads: null,
    density: null,
    morphology: null,
    pleural_pull: null,
    ai_raw_json: null,
    notes: null,
    created_at: '2026-04-18T00:00:00.000Z',
    updated_at: '2026-04-18T00:00:00.000Z',
  },
  {
    id: 'validation-ui-exam-breast-baseline',
    lesion_id: 'validation-ui-lesion-breast',
    exam_date: '2026-02-11',
    hospital: '验证接口医院B',
    size_x: 12.4,
    size_y: 6.9,
    size_z: null,
    tirads: null,
    echo_type: null,
    border: null,
    calcification: null,
    blood_flow: null,
    birads: '3',
    shape: '椭圆形',
    orientation: '平行',
    lung_rads: null,
    density: null,
    morphology: null,
    pleural_pull: null,
    ai_raw_json: null,
    notes: null,
    created_at: '2026-02-11T00:00:00.000Z',
    updated_at: '2026-02-11T00:00:00.000Z',
  },
  {
    id: 'validation-ui-exam-lung-latest',
    lesion_id: 'validation-ui-lesion-lung',
    exam_date: '2026-04-16',
    hospital: '验证接口医院C',
    size_x: 6.6,
    size_y: 4.2,
    size_z: null,
    tirads: null,
    echo_type: null,
    border: null,
    calcification: null,
    blood_flow: null,
    birads: null,
    shape: null,
    orientation: null,
    lung_rads: '2',
    density: '磨玻璃',
    morphology: '圆形',
    pleural_pull: 0,
    ai_raw_json: null,
    notes: null,
    created_at: '2026-04-16T00:00:00.000Z',
    updated_at: '2026-04-16T00:00:00.000Z',
  },
];

export const VALIDATION_UI_REMINDERS: Reminder[] = [
  {
    id: 'validation-ui-reminder-thyroid',
    lesion_id: 'validation-ui-lesion-thyroid',
    next_exam_date: '2026-05-18',
    source: 'manual',
    is_active: 1,
    created_at: '2026-04-20T00:00:00.000Z',
    updated_at: '2026-04-20T00:00:00.000Z',
  },
  {
    id: 'validation-ui-reminder-breast',
    lesion_id: 'validation-ui-lesion-breast',
    next_exam_date: '2026-08-18',
    source: 'auto',
    is_active: 1,
    created_at: '2026-04-18T00:00:00.000Z',
    updated_at: '2026-04-18T00:00:00.000Z',
  },
];

export function isValidationUiEvidenceRoute(): boolean {
  try {
    const search = globalThis.location?.search ?? '';
    const hash = globalThis.location?.hash ?? '';
    return `${search}&${hash}`.includes('validationUiSeed=repository');
  } catch {
    return false;
  }
}
