name: Preview Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-web:
    name: Deploy web preview
    type: deploy
    params:
      prod: false

  update-preview:
    name: Publish OTA update
    type: update
    params:
      branch: preview
